# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: sandboxrhg
# "service" is the name of this project. This will also be added to your AWS resource names.
service: reto-tecnico-backend-RHG
frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs20.x
  region: "us-east-1"
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource:
            - arn:aws:dynamodb:us-east-1:537124953041:table/Users
            - arn:aws:dynamodb:us-east-1:537124953041:table/fusionadosTable
            - arn:aws:dynamodb:us-east-1:537124953041:table/cacheTable

plugins:
  - serverless-offline
  - serverless-api-gateway-throttling

custom:
  # Configuraci칩n global de throttling para la API Gateway
  apiGatewayThrottling:
    maxRequestsPerSecond: 100   # M치ximo de solicitudes por segundo
    maxConcurrentRequests: 50   # M치ximo de solicitudes simult치neas

functions:
  fusionados:
    handler: fusionados.listar
    memorySize: 128  # 128MB
    timeout: 10      
    # reservedConcurrency: 2  # Limita la concurrencia
    events:
      - http:
          path: /fusionados/{people_id}
          method: get
  almacenar:
    handler: almacenar.registrar
    memorySize: 128  # 128MB
    timeout: 10      
    # reservedConcurrency: 2  # Limita la concurrencia
    events:
      - http:
          path: /almacenar
          method: post
  historial:
    handler: historial.listar
    memorySize: 128  # 128MB
    timeout: 10     
    # reservedConcurrency: 2  # Limita la concurrencia
    events:
      - http:
          path: /historial
          method: get
          throttling:
            maxRequestsPerSecond: 80
            maxConcurrentRequests: 40

resources:
  Resources:
    Users:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Users
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

    fusionadosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: fusionadosTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

    cacheTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: cacheTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
